CREATE TABLE pastStats (
	Year VARCHAR(7),
    Season_Type VARCHAR(20),
    PLAYER_ID INTEGER,
    RANK INTEGER,
    PLAYER VARCHAR(50),
    TEAM_ID INTEGER,
    TEAM VARCHAR(3),
    GP INTEGER,
    MIN NUMERIC(4,1),
    FGM NUMERIC(4,1),
    FGA NUMERIC(4,1),
    FG_PCT NUMERIC(4,3),
    FG3M NUMERIC(4,1),
    FG3A NUMERIC(4,1),
    FG3_PCT NUMERIC(4,3),
    FTM NUMERIC(4,1),
    FTA NUMERIC(4,1),
    FT_PCT NUMERIC(4,3),
    OREB NUMERIC(4,1),
    DREB NUMERIC(4,1),
    REB NUMERIC(4,1),
    AST NUMERIC(4,1),
    STL NUMERIC(4,1),
    BLK NUMERIC(4,1),
    TOV NUMERIC(4,1),
    PTS NUMERIC(4,1),
    EFF NUMERIC(4,1)
);

SELECT * FROM paststats;





